language: perl

os:
  - linux
  # - osx

# services:
  # - docker

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"

install:
  - cpanm --skip-satisfied -n -q Gedcom Parallel::Simple Encode WWW::Mechanize::GZip HTML::SimpleLinkExtor CHI DBD::SQLite Locale::Object::Country Locale::US Locale::CA Locale::SubCountry Memoize HTTP::Cookies Term::ANSIColor DateTime::Format::Natural Date::Calc File::Spec B::Lint warnings::unused IPC::System::Simple

script:
  - perl -c -MO=Lint ./gedgrave
  - perl -c -Mwarnings::unused ./ged2site
